apiVersion: v1
kind: Service
metadata:
  name: payments-webhook
  labels:
    app: payments-webhook
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: payments-ms
  type: NodePort
status:
  loadBalancer: {}
